# ==========================
# APPLICATION CONFIG
# ==========================
spring.application.name=inventory
server.port=8080
server.servlet.context-path=/api

# ==========================
# DATABASE CONNECTION
# ==========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações de Pool (Hikari) para estabilidade em Cloud
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# ==========================
# JPA / HIBERNATE SETTINGS
# ==========================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# IMPORTANTE: Evita erro de 'Tenant or user not found' ao carregar metadados
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Logs de SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true